version: "3.3"
services:
    php-fpm:
        build: ./php-fpm
        volumes:
            - ..:/var/www/:rw
            - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - my-library-network
    nginx:
        image: "1.20.0-alpine"
        volumes:
            - ..:/var/www/:rw
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        networks:
            - my-library-network
networks:
    my-library-network: