version: "3.9"
services:
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - PUID=${PUID}
                - PGID=${PGID}
        volumes:
            - ..:/var/www
        networks:
            - my-library-network

    nginx:
        build:
            context: ./nginx
        volumes:
            - ..:/var/www
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        networks:
            - my-library-network

    database:
        image: postgres:${POSTGRES_VERSION:-14}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-myLibrary}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-myLibraryPass}
            POSTGRES_USER: ${POSTGRES_USER:-myLibrary}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "${POSTGRESQL_HOST_PORT}:5432"
        networks:
            - my-library-network

volumes:
    db-data:

networks:
    my-library-network:
