version: "3.9"
services:
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - PUID=${PUID}
                - PGID=${PGID}
        volumes:
            - ..:/var/www
        networks:
            - my-library-network

    nginx:
        build:
            context: ./nginx
        volumes:
            - ..:/var/www
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        networks:
            - my-library-network
networks:
    my-library-network:
